### ISSUE TITLE
Loading Screen Not Displaying in Production

### ISSUE THREAD

**Issue by s-shemmee** [s-shemmee/ChatNow#1]
## Description
The loading screen works perfectly during development but is not showing up in the production environment. No errors or warnings were encountered during development, building, and deployment phases.

![Capture](https://github.com/s-shemmee/ChatNow/assets/56132945/0928f927-7d9a-4d65-9ce0-3f24eb0032cb)

**Comment by Earthyyy** [comment]
Have you checked this [solution](https://github.com/GriffinJohnston/ldrs/issues/24#issuecomment-2231328595) by the creator of ldrs?

It worked for me, I'm using React with Vite (prod setup)

**Comment by s-shemmee** [comment]
Hey @Earthyyy ! Thanks so much for pointing out the solution. It worked perfectly for me as well. Really appreciate your help! 😄

**Comment by Earthyyy** [comment]
Great! Good luck with the rest of the work
